# Generated by Django 3.0.8 on 2020-11-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_no', models.IntegerField()),
                ('cust_code', models.CharField(choices=[('B', 'B'), ('D', 'D'), ('W', 'W')], max_length=1)),
                ('days', models.IntegerField()),
                ('first_odo', models.IntegerField()),
                ('cust_state', models.CharField(choices=[('P', 'Punjab'), ('HR', 'Haryana'), ('H', 'Himachal'), ('UP', 'Uttar Pradesh')], max_length=30)),
            ],
        ),
    ]
