# Generated by Django 3.0.8 on 2020-11-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='cust_state',
            field=models.CharField(choices=[('Punjab', 'Punjab'), ('Haryana', 'Haryana'), ('Himachal', 'Himachal'), ('UP', 'Uttar Pradesh')], max_length=30),
        ),
    ]
