# Generated by Django 3.1.3 on 2020-11-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0002_auto_20201111_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(blank=True, max_length=50, null=True)),
                ('admin_email', models.CharField(max_length=50)),
                ('admin_username', models.CharField(max_length=50)),
                ('admin_password', models.CharField(max_length=50)),
            ],
        ),
    ]
