# Generated by Django 3.1.3 on 2021-01-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0007_billdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('c_name', models.CharField(blank=True, max_length=50, null=True)),
                ('phn_no', models.IntegerField()),
                ('c_code', models.CharField(max_length=1)),
                ('c_state', models.CharField(max_length=50)),
                ('no_days', models.IntegerField()),
                ('odo_first', models.IntegerField()),
                ('odo_final', models.IntegerField()),
                ('no_miles', models.IntegerField()),
                ('tax_rate', models.CharField(max_length=5)),
                ('amount_tax', models.CharField(max_length=20)),
                ('amount_due', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='BillDetails',
        ),
    ]
