# Generated by Django 3.1.3 on 2021-01-03 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0008_auto_20210103_1450'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BillDetail',
            new_name='BillDetails',
        ),
    ]
