# Generated by Django 3.1.3 on 2021-01-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0009_auto_20210103_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billdetails',
            name='amount_due',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='billdetails',
            name='amount_tax',
            field=models.IntegerField(),
        ),
    ]
